## 넘파이 array 데이터를 저장하기

In [28]:
import numpy as np
arr = np.arange(10)
arr2 = np.arange(15)
# array를 저장하자
np.save('some_array' , arr)

In [31]:
# load하자 불러오기. npy 파일
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
# savez는 여러개의 파일을 저장할 때 !!! 
np.savez('array_archive.npz', a = arr, b = arr2)

In [33]:
# savez한 'npz'파일을 불러온다
arch = np.load('array_archive.npz')

In [34]:
arch['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 이거는 압축해서 저장하는 방법.
np.savez_compressed('arrays_compressed.npz', a=arr, b=arr2)