## 구간나누기 !! 연습해보자 pd.cut

In [19]:
import pandas as pd 
import numpy as np

In [20]:
ages = [20,22,25,27,21,23,37,31,61,45,41,32]
bins = [18,25,35,60,100]

# 판다스의 cut 기능을 써 보자 !

In [21]:
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [14]:
# 그 숫자가 어느 구간인지 ?
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [15]:
# 구간 보기
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [17]:
# 구간에 들어갈 숫자 세기 
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

# 그 구간에 이름 붙여주기도 가능 ! (재밌음)

In [23]:
# 이렇게 구간에다가 이름붙이자! 유용할듯. labels 주자 
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels = group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

# 내가 설정한 구간이 아니라 equal-length로 n개 나누려면 ?

In [28]:
data = np.random.rand(20)
data

array([0.87957387, 0.21781801, 0.26153425, 0.00832541, 0.18564489,
       0.83446072, 0.91582214, 0.34078611, 0.09870593, 0.6113148 ,
       0.1298231 , 0.45527274, 0.8382223 , 0.28525266, 0.43345932,
       0.39870506, 0.33762729, 0.89253574, 0.26908091, 0.21249658])

In [30]:
#  이렇게 구간이 아니라 숫자로 주면 된다 !!!! precision은 ? 소숫점 두 자리까지 표시하라는 것 
pd.cut(data, 4, precision=2)

[(0.69, 0.92], (0.0074, 0.24], (0.24, 0.46], (0.0074, 0.24], (0.0074, 0.24], ..., (0.24, 0.46], (0.24, 0.46], (0.69, 0.92], (0.24, 0.46], (0.0074, 0.24]]
Length: 20
Categories (4, interval[float64]): [(0.0074, 0.24] < (0.24, 0.46] < (0.46, 0.69] < (0.69, 0.92]]

# quantiles. 즉, 분위수로 나누기 !!!

In [32]:
data = np.random.randn(1000) # normally distributed.
data

array([ 2.76782204e-01, -3.04580402e-01, -7.52059091e-03, -1.58767866e+00,
       -1.87575919e+00,  4.31778636e-01,  3.42139633e-01,  1.14671392e-01,
       -4.97562252e-01,  1.93128753e-01,  7.67178982e-01, -2.08732496e+00,
        1.98350290e-01, -5.08464435e-01,  1.10190821e+00, -3.77572773e-01,
       -4.18700792e-02,  4.85270698e-01,  1.61514516e-01,  5.32024857e-01,
        1.64651217e+00,  1.45878987e+00,  2.23328403e+00,  1.67187555e+00,
       -6.42652245e-01,  4.52454954e-01,  2.99532128e-01, -1.73500720e+00,
       -6.85608686e-01,  1.47825210e+00,  2.70197674e-01,  9.49225969e-01,
       -9.70131746e-01, -3.88290361e-02,  1.36778873e+00,  2.45122640e-02,
        5.71870480e-01,  4.33163700e-01, -1.30637669e+00,  8.64508291e-01,
        6.39875506e-01,  9.41895254e-02, -4.14438963e-01,  2.42882110e-01,
        9.25625377e-01,  7.92478507e-01, -3.27343905e-01,  1.67010247e-01,
       -6.92457806e-01,  1.19200560e+00,  3.15195641e-01,  7.30306085e-01,
       -8.28557459e-02, -

In [34]:
# Cut into quartiles 
cats = pd.qcut(data,4)

In [36]:
# 이렇게 나옴. 첨엔 각 숫자들이 어느 구간에 속하는지고, 맨 마지막이 그 카테고리들 나누어놓은거 같다!
cats

[(0.0954, 0.646], (-0.571, 0.0954], (-0.571, 0.0954], (-3.4539999999999997, -0.571], (-3.4539999999999997, -0.571], ..., (-0.571, 0.0954], (0.0954, 0.646], (0.0954, 0.646], (-0.571, 0.0954], (-0.571, 0.0954]]
Length: 1000
Categories (4, interval[float64]): [(-3.4539999999999997, -0.571] < (-0.571, 0.0954] < (0.0954, 0.646] < (0.646, 2.895]]

## 뭐 이렇게 내가 quantile을 일정하지 않은 간격으로도 줄 수 있음!

In [43]:
data = [1,2,3,4,5,6,7,8,9,10]
data

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [45]:
# 여전히 qcut는 이용!
pd.qcut(data, [0,0.1,0.9,1])

[(0.999, 1.9], (1.9, 9.1], (1.9, 9.1], (1.9, 9.1], (1.9, 9.1], (1.9, 9.1], (1.9, 9.1], (1.9, 9.1], (1.9, 9.1], (9.1, 10.0]]
Categories (3, interval[float64]): [(0.999, 1.9] < (1.9, 9.1] < (9.1, 10.0]]