## get_dummies : 이거 머신러닝 돌리기 전에 원핫인코딩하는 것임
 - 카테고리 범주들을 1,0으로 표현. 
 - 그냥 이런 방식으로 하는구나 정도만 알면 될듯. 아직 머신러닝하는거 아니니깐.

In [52]:
import pandas as pd
import numpy as np

In [53]:
mnames = ['movie_id', 'title', 'genres']
movies = pd.read_table('datasets/movielens/movies.dat', sep='::', header=None, names=mnames)

C:\Users\USER\anaconda3\lib\site-packages\ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  


In [54]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [55]:
all_genres = []
for x in movies.genres :
    all_genres.extend(x.split('|'))
    
all_genres

['Animation',
 "Children's",
 'Comedy',
 'Adventure',
 "Children's",
 'Fantasy',
 'Comedy',
 'Romance',
 'Comedy',
 'Drama',
 'Comedy',
 'Action',
 'Crime',
 'Thriller',
 'Comedy',
 'Romance',
 'Adventure',
 "Children's",
 'Action',
 'Action',
 'Adventure',
 'Thriller',
 'Comedy',
 'Drama',
 'Romance',
 'Comedy',
 'Horror',
 'Animation',
 "Children's",
 'Drama',
 'Action',
 'Adventure',
 'Romance',
 'Drama',
 'Thriller',
 'Drama',
 'Romance',
 'Thriller',
 'Comedy',
 'Action',
 'Action',
 'Comedy',
 'Drama',
 'Crime',
 'Drama',
 'Thriller',
 'Thriller',
 'Drama',
 'Sci-Fi',
 'Drama',
 'Romance',
 'Drama',
 'Drama',
 'Romance',
 'Adventure',
 'Sci-Fi',
 'Drama',
 'Drama',
 'Drama',
 'Sci-Fi',
 'Adventure',
 'Romance',
 "Children's",
 'Comedy',
 'Drama',
 'Drama',
 'Romance',
 'Drama',
 'Documentary',
 'Comedy',
 'Comedy',
 'Romance',
 'Drama',
 'Drama',
 'War',
 'Action',
 'Crime',
 'Drama',
 'Drama',
 'Action',
 'Adventure',
 'Comedy',
 'Drama',
 'Drama',
 'Romance',
 'Crime',
 'Thrill

In [56]:
len(all_genres)

6408

In [57]:
genres = pd.unique(all_genres)
genres,len(genres)

(array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
        'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
        'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
        'Western'], dtype=object),
 18)

In [58]:
zero_matrix = np.zeros((len(movies), len(genres)))
zero_matrix, zero_matrix.shape

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 (3883, 18))

In [59]:
dummies = pd.DataFrame(zero_matrix, columns = genres)
dummies

Animation  Children's  Comedy  Adventure  Fantasy  Romance  Drama  \
0           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
1           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
2           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
4           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
...         ...         ...     ...        ...      ...      ...    ...   
3878        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3879        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3880        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3881        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3882        0.0         0.0     0.0        0.0      0.0      0.0    0.0   

      Action  Crime  Thriller  Horror  Sci-Fi  Documentary  War  Musical  \
0        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
1        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
2        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
4        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
...      ...    ...       ...     ...     ...          ...  ...      ...   
3878     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3879     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3880     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3881     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3882     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   

      Mystery  Film-Noir  Western  
0         0.0        0.0      0.0  
1         0.0        0.0      0.0  
2         0.0        0.0      0.0  
3         0.0        0.0      0.0  
4         0.0        0.0      0.0  
...       ...        ...      ...  
3878      0.0        0.0      0.0  
3879      0.0        0.0      0.0  
3880      0.0        0.0      0.0  
3881      0.0        0.0      0.0  
3882      0.0        0.0      0.0  

[3883 rows x 18 columns]

In [60]:
gen = movies.genres[0]
gen.split('|')

['Animation', "Children's", 'Comedy']

In [61]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2], dtype=int64)

In [62]:
for i,gen in enumerate(movies.genres) :
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1

In [63]:
dummies

Animation  Children's  Comedy  Adventure  Fantasy  Romance  Drama  \
0           1.0         1.0     1.0        0.0      0.0      0.0    0.0   
1           0.0         1.0     0.0        1.0      1.0      0.0    0.0   
2           0.0         0.0     1.0        0.0      0.0      1.0    0.0   
3           0.0         0.0     1.0        0.0      0.0      0.0    1.0   
4           0.0         0.0     1.0        0.0      0.0      0.0    0.0   
...         ...         ...     ...        ...      ...      ...    ...   
3878        0.0         0.0     1.0        0.0      0.0      0.0    0.0   
3879        0.0         0.0     0.0        0.0      0.0      0.0    1.0   
3880        0.0         0.0     0.0        0.0      0.0      0.0    1.0   
3881        0.0         0.0     0.0        0.0      0.0      0.0    1.0   
3882        0.0         0.0     0.0        0.0      0.0      0.0    1.0   

      Action  Crime  Thriller  Horror  Sci-Fi  Documentary  War  Musical  \
0        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
1        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
2        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
4        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
...      ...    ...       ...     ...     ...          ...  ...      ...   
3878     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3879     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3880     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3881     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3882     0.0    0.0       1.0     0.0     0.0          0.0  0.0      0.0   

      Mystery  Film-Noir  Western  
0         0.0        0.0      0.0  
1         0.0        0.0      0.0  
2         0.0        0.0      0.0  
3         0.0        0.0      0.0  
4         0.0        0.0      0.0  
...       ...        ...      ...  
3878      0.0        0.0      0.0  
3879      0.0        0.0      0.0  
3880      0.0        0.0      0.0  
3881      0.0        0.0      0.0  
3882      0.0        0.0      0.0  

[3883 rows x 18 columns]

In [64]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [65]:
movies_windic

movie_id                               title  \
0            1                    Toy Story (1995)   
1            2                      Jumanji (1995)   
2            3             Grumpier Old Men (1995)   
3            4            Waiting to Exhale (1995)   
4            5  Father of the Bride Part II (1995)   
...        ...                                 ...   
3878      3948             Meet the Parents (2000)   
3879      3949          Requiem for a Dream (2000)   
3880      3950                    Tigerland (2000)   
3881      3951             Two Family House (2000)   
3882      3952               Contender, The (2000)   

                            genres  Genre_Animation  Genre_Children's  \
0      Animation|Children's|Comedy              1.0               1.0   
1     Adventure|Children's|Fantasy              0.0               1.0   
2                   Comedy|Romance              0.0               0.0   
3                     Comedy|Drama              0.0               0.0   
4                           Comedy              0.0               0.0   
...                            ...              ...               ...   
3878                        Comedy              0.0               0.0   
3879                         Drama              0.0               0.0   
3880                         Drama              0.0               0.0   
3881                         Drama              0.0               0.0   
3882                Drama|Thriller              0.0               0.0   

      Genre_Comedy  Genre_Adventure  Genre_Fantasy  Genre_Romance  \
0              1.0              0.0            0.0            0.0   
1              0.0              1.0            1.0            0.0   
2              1.0              0.0            0.0            1.0   
3              1.0              0.0            0.0            0.0   
4              1.0              0.0            0.0            0.0   
...            ...              ...            ...            ...   
3878           1.0              0.0            0.0            0.0   
3879           0.0              0.0            0.0            0.0   
3880           0.0              0.0            0.0            0.0   
3881           0.0              0.0            0.0            0.0   
3882           0.0              0.0            0.0            0.0   

      Genre_Drama  ...  Genre_Crime  Genre_Thriller  Genre_Horror  \
0             0.0  ...          0.0             0.0           0.0   
1             0.0  ...          0.0             0.0           0.0   
2             0.0  ...          0.0             0.0           0.0   
3             1.0  ...          0.0             0.0           0.0   
4             0.0  ...          0.0             0.0           0.0   
...           ...  ...          ...             ...           ...   
3878          0.0  ...          0.0             0.0           0.0   
3879          1.0  ...          0.0             0.0           0.0   
3880          1.0  ...          0.0             0.0           0.0   
3881          1.0  ...          0.0             0.0           0.0   
3882          1.0  ...          0.0             1.0           0.0   

      Genre_Sci-Fi  Genre_Documentary  Genre_War  Genre_Musical  \
0              0.0                0.0        0.0            0.0   
1              0.0                0.0        0.0            0.0   
2              0.0                0.0        0.0            0.0   
3              0.0                0.0        0.0            0.0   
4              0.0                0.0        0.0            0.0   
...            ...                ...        ...            ...   
3878           0.0                0.0        0.0            0.0   
3879           0.0                0.0        0.0            0.0   
3880           0.0                0.0        0.0            0.0   
3881           0.0                0.0        0.0            0.0   
3882           0.0                0.0        0.0            0.0   

      Genre_Myste

# cut 이용해 아예 구간별로 원핫인코딩하기?

In [66]:
values = np.random.rand(10)
values

array([0.38949871, 0.96399867, 0.07072534, 0.65012902, 0.1206889 ,
       0.0885078 , 0.81387781, 0.03049387, 0.65802651, 0.76742476])

In [67]:
bins = [0,0.2,0.4,0.6,0.8,1]
bins

[0, 0.2, 0.4, 0.6, 0.8, 1]

In [70]:
# 이렇게 하면 구간별로 세면서 인코딩 ok
pd.get_dummies(pd.cut(values,bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           1           0           0           0
1           0           0           0           0           1
2           1           0           0           0           0
3           0           0           0           1           0
4           1           0           0           0           0
5           1           0           0           0           0
6           0           0           0           0           1
7           1           0           0           0           0
8           0           0           0           1           0
9           0           0           0           1           0