### 간단하게 - array 슬라이싱 = 리스트랑 그냥 똑같음 !

In [131]:
import numpy as np

In [132]:
arr = np.arange(10)

In [133]:
arr[1:4]

array([1, 2, 3])

In [134]:
arr[1]  = 100000
arr

array([     0, 100000,      2,      3,      4,      5,      6,      7,
            8,      9])

In [135]:
arr[:] = 80
arr

array([80, 80, 80, 80, 80, 80, 80, 80, 80, 80])

### 만약 array 가 high demensional 일 경우에 :
 - array[1]이런거는 더이상 숫자가 아니라 하나의 array다.
 

In [136]:
# ex
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

In [137]:
# 이렇게 접근가능. 연산속도를 확 줄여줌
arr2d[0][2]

3

## 이 부분은 조금 복잡함 ! - 3차원인경우 인덱스는 ?

In [138]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [139]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## 2x2x3인 경우에 [0]하면 ?

In [140]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [141]:
arr3d[0] = 13
arr3d

array([[[13, 13, 13],
        [13, 13, 13]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## arr3d[1,0] - 인덱스가(1,0)으로 시작하는 것들 

In [142]:
# ex  - 7,8,9 각각은 (1,0,0), (1,0,1), (1,0,2)인 것임
arr3d[1,0]

array([7, 8, 9])

## 이제 Slicing

In [143]:
# 1차원은 list랑 똑같음
arr = np.array([0,1,2,3,4,64,64,64,8,9])
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [144]:
# 2차원부터는 다름
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [145]:
# select first two rwos of arr2d임!
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [146]:
# 이렇게도 slicing 가능 ! 
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [147]:
# randn은 -1~1 정규분포를 m x n 행렬에 채움
data = np.random.randn(7,4)

### Boolean 값 Indexing

In [148]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [149]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [150]:
data

array([[ 1.11516069, -1.06861451,  0.30533298,  0.31225209],
       [ 0.94611741,  1.42166409, -0.69584875, -1.23859654],
       [-0.10908205,  1.10836072,  0.29996765, -1.75529358],
       [ 1.01581891, -1.56918141, -0.34960182, -0.68298969],
       [ 0.70227827, -0.88007615,  1.21297558, -0.78972693],
       [-0.41088374,  0.21255092, -1.49648169,  1.15653414],
       [-1.62658096, -0.74184588, -1.30302244, -0.44969586]])

In [151]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [152]:
# data에서 인덱스 0,3의 행을 가져온다. 이 떄 data와 names 의 size가 맞아야
data[names == 'Bob']

array([[ 1.11516069, -1.06861451,  0.30533298,  0.31225209],
       [ 1.01581891, -1.56918141, -0.34960182, -0.68298969]])

In [153]:
data[names == 'Bob', 2:]

array([[ 0.30533298,  0.31225209],
       [-0.34960182, -0.68298969]])

In [154]:
data[names == 'Bob', 3]

array([ 0.31225209, -0.68298969])

In [155]:
# not Bob !
data[~(names == 'Bob')]

array([[ 0.94611741,  1.42166409, -0.69584875, -1.23859654],
       [-0.10908205,  1.10836072,  0.29996765, -1.75529358],
       [ 0.70227827, -0.88007615,  1.21297558, -0.78972693],
       [-0.41088374,  0.21255092, -1.49648169,  1.15653414],
       [-1.62658096, -0.74184588, -1.30302244, -0.44969586]])

In [156]:
# not Bob 이렇게도 가능 !
cond = names == 'Bob'

In [157]:
data[~cond]

array([[ 0.94611741,  1.42166409, -0.69584875, -1.23859654],
       [-0.10908205,  1.10836072,  0.29996765, -1.75529358],
       [ 0.70227827, -0.88007615,  1.21297558, -0.78972693],
       [-0.41088374,  0.21255092, -1.49648169,  1.15653414],
       [-1.62658096, -0.74184588, -1.30302244, -0.44969586]])

In [158]:
# 여러 조건 같이 걸기 |는 or 이고 &는 and 
mask = (names == 'Bob') | (names == 'Will')

In [159]:
mask

array([ True, False,  True,  True,  True, False, False])

In [160]:
data

array([[ 1.11516069, -1.06861451,  0.30533298,  0.31225209],
       [ 0.94611741,  1.42166409, -0.69584875, -1.23859654],
       [-0.10908205,  1.10836072,  0.29996765, -1.75529358],
       [ 1.01581891, -1.56918141, -0.34960182, -0.68298969],
       [ 0.70227827, -0.88007615,  1.21297558, -0.78972693],
       [-0.41088374,  0.21255092, -1.49648169,  1.15653414],
       [-1.62658096, -0.74184588, -1.30302244, -0.44969586]])

In [161]:
data[mask]

array([[ 1.11516069, -1.06861451,  0.30533298,  0.31225209],
       [-0.10908205,  1.10836072,  0.29996765, -1.75529358],
       [ 1.01581891, -1.56918141, -0.34960182, -0.68298969],
       [ 0.70227827, -0.88007615,  1.21297558, -0.78972693]])

# 이렇게 응용하자!

In [162]:
# 0 미만 값들 찾아보기
data[data<0] =  0 
data

array([[1.11516069, 0.        , 0.30533298, 0.31225209],
       [0.94611741, 1.42166409, 0.        , 0.        ],
       [0.        , 1.10836072, 0.29996765, 0.        ],
       [1.01581891, 0.        , 0.        , 0.        ],
       [0.70227827, 0.        , 1.21297558, 0.        ],
       [0.        , 0.21255092, 0.        , 1.15653414],
       [0.        , 0.        , 0.        , 0.        ]])

In [163]:
# name이 Joe가 아닌 값들 찾기 
data[names != 'Joe'] = 7 
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.94611741, 1.42166409, 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.21255092, 0.        , 1.15653414],
       [0.        , 0.        , 0.        , 0.        ]])

## 인덱싱 응용 하자 - Fancy Indexing

In [165]:
arr = np.empty((8,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [171]:
for i in range(8) : 
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [172]:
# select out a subset of the rows :
arr[[4,3,5,7]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [5., 5., 5., 5.],
       [7., 7., 7., 7.]])

In [176]:
# 이런식으로 역으로도 추출 가능 
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [178]:
arr = np.arange(32).reshape((8, 4))

In [182]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [184]:
# 1) 이런식으로 뽑아내거나 
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [197]:
# 2) 이렇게도 가능
arr[[1,5,7,2]] 

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [198]:
# 3) 이렇게도 가능
arr[[1,5,7,2]][:]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [199]:
# 4) 이렇게도 가능
arr[[1,5,7,2]][:, [0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])