# 넘파이 배워보자

In [99]:
# array 생성
import numpy as np
my_arr = np.arange(1000000)

## 이 넘파이 100만개의 array를 파이썬 리스트랑 비교

In [100]:
my_list = list(range(1000000))

In [101]:
%time for _ in range(10) : my_arr2 = my_arr *2

Wall time: 25 ms


In [102]:
%time for _ in range(10) : my_list2 = [x*2 for x in my_list]

Wall time: 925 ms


 - 위의 결론 : numpy의 array로하는 계산이 훨씬 빠르다 !

## ndarray :  array의 n차원 형태 (N-dimensional)

- ndarray에서 각 요소는 same dtype 이어야 한다 !
- "array" = "NumPy array" = "ndarray" 같은 말이라고 보면 됨

In [103]:
data = np.random.randn(2,3)

In [104]:
data

array([[-0.76654927,  1.14439172,  0.38831931],
       [ 1.88972856,  1.26736726, -0.45796543]])

In [105]:
data * 10

array([[-7.66549271, 11.44391722,  3.88319307],
       [18.89728556, 12.67367262, -4.57965427]])

In [106]:
data * 2 == data+data

array([[ True,  True,  True],
       [ True,  True,  True]])

 - dtype ( data type ) 


In [107]:
data.shape
data.dtype

dtype('float64')

 #### Array 생성하기 
  - array 함수 이용함. 여기 안에는 리스트든 뭐든 sequence-like object 넣으면 가능함 

In [108]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)

In [109]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

 #### 중첩된 sequence 즉 Nested sequences가 만약 같은 길이의 리스트 같은 경우에는 shape가 달라진다 - Multidimensional array로. 

In [110]:
# 리스트들의 리스트, data2
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)

In [111]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [112]:
arr2.ndim

2

In [113]:
arr2.shape

(2, 4)

In [114]:
arr2.dtype

dtype('int32')

In [115]:
# zero로 만들기
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [116]:
# 1들로 채우기
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [117]:
# 이런식으로 튜플로 형태 지정해줄 수 있음
a = np.zeros((3,6))
a

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [118]:
a.dtype

dtype('float64')

In [119]:
# empty는 0과는 좀 다름. 타입도 다르고, empty넣어서 0이 아닌 다른게 나올수도 있음
b= np.empty((2,3,2))
b

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [120]:
b.dtype

dtype('float64')

###### 또 ARRAY-VALUED version of 파이썬 range 함수는 arange임

In [121]:
# 1) arange : range함수랑 비슷한데 이걸 array로 뽑음
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [122]:
# 2) array : 입력된 data를 array로 만든다
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [123]:
# 3) asarray : array로 바꾸어줌. 
np.asarray([1,2,3])

array([1, 2, 3])

#### dtype 부분 

In [80]:
arr1 = np.array([1,2,3], dtype =np.float64)

In [81]:
arr1.dtype

dtype('float64')

#### dtype 변환

In [84]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int32')

In [85]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

#### 형변환하면서 밑부분은 잘림

In [91]:
arr = np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [125]:
arr.astype(np.int64)

array([ 3, -1, -2,  0, 12, 10], dtype=int64)

### 그니까 이런거는 행렬의 곱과 달리 element-wise라고 하는데 그냥 각 위치 숫자들끼리 그냥 단순히 곱한것임 

 - 이런게 array에서 가능한데, 이거 때문에 array가 batch ooperation이 가능한, 중요한 기능이라고 할 수 있는 것

In [143]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])

In [144]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [146]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [147]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [148]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [149]:
arr2 = np.array([[0,4,1],[7,2,12]])

In [152]:
# 이렇게 비교도 가능 
arr2 > arr 

array([[False,  True, False],
       [ True, False,  True]])