In [1]:
import pandas as pd
import numpy as np

## 유니크한 값 뽑아내기 기능!

In [29]:
# 일단 시리즈로 해보기
obj = pd.Series(['c','a','d','a','a','b','b','c','c'])
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [28]:
# unique 사용
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [32]:
# 같은 작업을 데이터 프레임도 가능
dtf = pd.DataFrame({'a' : [1,3,3,4], 'b' : [9,9,9,9]})
dtf

a  b
0  1  9
1  3  9
2  3  9
3  4  9

In [36]:
# 어차피 이렇게 뽑으면 시리즈임
dtf['a'].unique()

array([1, 3, 4], dtype=int64)

In [37]:
dtf['b'].unique()

array([9], dtype=int64)

## value frequency를 세보자 !

In [40]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [42]:
# a,b,c,d 각각 몇 개씩
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [48]:
# 같은것을 pandas 로 할 수 있음
pd.value_counts(obj.values)

a    3
c    3
b    2
d    1
dtype: int64

## 조건에 해당하는 subset 뽑아내보자 

In [60]:
mask = obj.isin(['b','c'])

In [61]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [62]:
# 이런식으로 mask가 True인 것만 뽑아낼 수 있음
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

## get_indexer : 잘은 이해 안감

In [77]:
to_match = pd.Series(['c','a','b','b','c','a'])

In [78]:
to_match

0    c
1    a
2    b
3    b
4    c
5    a
dtype: object

In [79]:
unique_vals = pd.Series(['c','b','a'])

In [74]:
unique_vals

0    c
1    b
2    a
dtype: object

In [75]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

## 이거를 언제 쓸지는 잘 모르겠지만 ... 
 -  distinct value 세는 또 다른방법!

In [134]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
 'Qu2': [2, 3, 1, 9, 3],
 'Qu3': [1, 5, 11, 4, 4]})

In [135]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1   11
3    3    9    4
4    4    3    4

In [136]:
result = data.apply(pd.value_counts, axis=0)

In [138]:
# 보니까 이건 Qu1 1은 Qu1에서 1이 1개라는 것. Qu3에서 4는 2개였음, Qu2에서 9는 한 개였음. ok 
result

Qu1  Qu2  Qu3
1   1.0  1.0  1.0
2   NaN  1.0  NaN
3   2.0  2.0  NaN
4   2.0  NaN  2.0
5   NaN  NaN  1.0
9   NaN  1.0  NaN
11  NaN  NaN  1.0