### Sort 하기 - 넘파이

In [38]:
import numpy as np
arr = np.random.randn(6)

In [39]:
arr

array([-0.67805932, -0.88474706, -0.17475027, -0.7735073 ,  0.30422022,
       -1.67209013])

In [40]:
# 기본적으로 행 안에서 바꾸는거같음. 행 번째는 그대로 두고 행 안에서
arr.sort()

In [8]:
arr

array([-0.31067195, -0.30471408,  0.27016603,  0.32811665,  0.85368498,
        1.11173369])

In [32]:
arr = np.random.randn(5,3)

In [33]:
arr

array([[-1.14271186, -1.70289334,  0.08797068],
       [ 1.4657937 , -3.16895047, -0.81868807],
       [-0.45591448,  2.14321733,  0.50482727],
       [-1.7410874 ,  1.42807813, -1.17815606],
       [ 0.11205232, -0.25222103,  0.97504667]])

In [34]:
# 잘 보면 열들은 똑같고 해당 열 안에서 순서 바뀜
arr.sort(0)

In [35]:
arr

array([[-1.7410874 , -3.16895047, -1.17815606],
       [-1.14271186, -1.70289334, -0.81868807],
       [-0.45591448, -0.25222103,  0.08797068],
       [ 0.11205232,  1.42807813,  0.50482727],
       [ 1.4657937 ,  2.14321733,  0.97504667]])

In [36]:
# 잘 보면 행은 똑같음. 각 행 안에서 바뀜!
arr.sort(1)

In [37]:
arr

array([[-3.16895047, -1.7410874 , -1.17815606],
       [-1.70289334, -1.14271186, -0.81868807],
       [-0.45591448, -0.25222103,  0.08797068],
       [ 0.11205232,  0.50482727,  1.42807813],
       [ 0.97504667,  1.4657937 ,  2.14321733]])

## quantile - 분위수 구하기 ! 즉 몇 퍼센트에 해당하는지 그거 구해보자

In [78]:
# 1000개의 숫자들이 생긴다
large_arr = np.random.randn(1000)

In [79]:
# 이러면 작은거부터 큰것으로 오름차순으로 정리 된다!
large_arr.sort()
large_arr

array([-2.88497960e+00, -2.84448245e+00, -2.75250205e+00, -2.47891461e+00,
       -2.44286866e+00, -2.36920161e+00, -2.36408789e+00, -2.32816208e+00,
       -2.29082663e+00, -2.22938778e+00, -2.14340070e+00, -2.06672886e+00,
       -2.06548415e+00, -2.04881575e+00, -2.03921250e+00, -2.03648244e+00,
       -2.03630007e+00, -2.02705926e+00, -2.00962690e+00, -2.00903070e+00,
       -1.98638351e+00, -1.98440150e+00, -1.94893891e+00, -1.94883557e+00,
       -1.94751486e+00, -1.94730549e+00, -1.91639529e+00, -1.89638772e+00,
       -1.89120020e+00, -1.88754104e+00, -1.84121884e+00, -1.83917593e+00,
       -1.83023662e+00, -1.80510564e+00, -1.79199457e+00, -1.77553638e+00,
       -1.76176838e+00, -1.73637986e+00, -1.73373915e+00, -1.71405310e+00,
       -1.69873526e+00, -1.69831058e+00, -1.68832977e+00, -1.68679724e+00,
       -1.63245539e+00, -1.63244771e+00, -1.62178911e+00, -1.61973974e+00,
       -1.61555607e+00, -1.61553385e+00, -1.60269674e+00, -1.59530404e+00,
       -1.59242016e+00, -

In [80]:
# 0.05부분, 즉 하위 5%에 해당하는 부분을 만들어낸다
large_arr[int(0.05 * len(large_arr))]

-1.6026967359150501

### 유니크한 값들 뽑아내기 !

In [86]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [87]:
# 유니크
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [91]:
ints = np.array([3,3,3,2,2,1,1,4,4])
np.unique(ints)

array([1, 2, 3, 4])

In [94]:
# 이렇게 sort도 가능!
sorted(set(names))

['Bob', 'Joe', 'Will']

In [98]:
# in1d(x,y)는 검색해보면 알겠지만 첫 째 배열 x가 둘째 배열 y의 원소를 포함하는지 여부임
# 관련 기능들로는 intersect1d , union1d, setdiff1d 등이 있음.
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

## array 관련 operations 
 - unique(x) : sorted unique elements x를 뽑아냄
 - intersect1d(x,y) : x와 y의 common elements를 뽑아냄
 - union1d(x,y) : sorted union of elements를 뽑아냄
 - in1d(x,y) : 불린값 뽑아냄, x가 y의 원소들 안에 있는지
 - setdiff1d(x,y) : set들을 difference즉 x들 중에서 y에 없는거 뽑아냄
 - setxor1d(x,y) : difference 두 개임. 양쪽으로. 즉 x에있는거,y에없는거. y에있고 x에없는거 

In [115]:
x = np.array([1,1,2,3,4,5,6,7])
y = np.array([10,10,20,30,40,5,6,7])

In [106]:
# 유니크
np.unique(x)

array([1, 2, 3, 4, 5, 6, 7])

In [109]:
# 인터섹트
np.intersect1d(x, y)

array([5, 6, 7])

In [111]:
# 유니온. 합쳐서 유니크한
np.union1d(x,y)

array([ 1,  2,  3,  4,  5,  6,  7, 10, 20, 30, 40])

In [116]:
# 불린값으로. 지금 이것들 해보면 알겠지만 x,y가 길이가 동일할 필요는 없음. 
np.in1d(x,y)

array([False, False, False, False, False,  True,  True,  True])

In [117]:
# set diffrence즉 x와 y 차집합
np.setdiff1d(x,y)

array([1, 2, 3, 4])

In [118]:
# 차집합 양쪽 방향으로
np.setxor1d(x,y)

array([ 1,  2,  3,  4, 10, 20, 30, 40])